---
wg_user_list:
  user_1:
    {
      username: "solopc",
      private_ip: "10.0.0.11",
      default_route: yes,
      wg_dns_enabled: no,
      remove: no,
    }
  user_2:
    {
      username: "solot",
      private_ip: "10.0.0.12",
      default_route: yes,
      wg_dns_enabled: yes,
      remove: no,
    }
